### ISSUE TITLE
SXFM - Parsing AlternativeGroup

### ISSUE THREAD

**Issue by Kallistos** [Kallistos/SPLConqueror#1]
[testing.sxfm.zip](https://github.com/Kallistos/SPLConqueror/files/4857623/testing.sxfm.zip)

Alternative group: _Ge__3
g_3_2 excludes children of g_3_1 instead of g_3_1 itself

**Comment by ChristianKaltenecker** [comment]
This only affects the parser of sxfm models.
I couldn't reproduce it using the following xml file.
[test.zip](https://github.com/Kallistos/SPLConqueror/files/4877668/test.zip)

I am currently working on fixing the issue in the sxfm parser.
